const express = require("express");
const { z } = require("zod");
const svc = require("./notifications.service");
const { asyncHandler, AppError } = require("../../utils/asyncHandler");
const { requireAuth } = require("../../middleware/auth");

const router = express.Router();
router.use(requireAuth);

router.get("/", asyncHandler(async (req, res) => {
  res.json(await svc.listForUser(req.user.id));
}));

router.patch("/:id/read", asyncHandler(async (req, res) => {
  res.json(await svc.markRead(req.user.id, req.params.id));
}));

// --- Mobile app device registration ---
// Registering a device is what makes a donor matchable (see
// requests/matching.js), so this is deliberately restricted to real accounts:
// a public OTP session has no User row to attach a device to.
function requireAccount(req, res, next) {
  if (!req.user?.role) {
    return next(new AppError("This action requires a registered account", 403));
  }
  next();
}

const deviceSchema = z.object({
  // Generated by the app on first launch and stable thereafter — proves the
  // app is installed even when Firebase/push isn't configured.
  installId: z.string().min(8).max(200),
  // Only present once Firebase is set up; absent is normal, not an error.
  pushToken: z.string().min(10).max(4096).optional(),
  platform: z.enum(["android", "ios"]).optional(),
});

router.post("/devices", requireAccount, asyncHandler(async (req, res) => {
  const data = deviceSchema.parse(req.body);
  await svc.registerDevice(req.user.id, data);
  res.json({ ok: true });
}));

router.delete("/devices", requireAccount, asyncHandler(async (req, res) => {
  const { installId } = z.object({ installId: z.string().min(8).max(200) }).parse(req.body);
  res.json(await svc.unregisterDevice(req.user.id, installId));
}));

module.exports = router;
